#!/bin/sh
timestamp=`date +"%Y%m%d-%H%M"`

mkdir -p ${HOME}/pub/qso-party/cqp_backups

ssh tepperly@robot.cqp.org ${HOME}/cqpbackup ${timestamp}
scp tepperly@robot.cqp.org:tmp/backup${timestamp}.tar.xz ${HOME}/pub/qso-party/cqp_backups/
ssh tepperly@robot.cqp.org /bin/rm -rf tmp/backup${timestamp}.tar.xz
